"""Types for generating pipeline results."""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field, TypeAdapter

from prp.models.enums import AnalysisSoftware, AnalysisType
from prp.models.manifest import URI
from prp.models.base import RWModel

SCHEMA_VERSION: int = 2


class ReferenceGenome(RWModel):
    """Reference genome."""

    name: str
    accession: str
    fasta: str
    fasta_index: str
    genes: str


class IgvAnnotationTrack(RWModel):
    """IGV annotation track data."""

    name: str  # track name to display
    file: str  # path to the annotation file


class CdmRecord(BaseModel):
    """Qc results container for CDM"""

    id: str
    software: AnalysisSoftware
    result: Any


CdmRecords = TypeAdapter(list[CdmRecord])


class PipelineArtifact(BaseModel):
    """Describe a file generated by the pipeline."""

    software_name: AnalysisSoftware
    software_version: str
    uri: URI


class PipelineDefinition(BaseModel):
    """Static metadata about the pipeline code itself."""

    name: str
    version: str
    commit: str | None = None
    release_life_cycle: Literal["development", "staging", "production", "unknown"]


class PipelineRunConfig(BaseModel):
    """Configuration used for this specific execution."""

    command: str
    analysis_profile: list[str] = Field(default_factory=list)
    configuration_files: list[str] = Field(default_factory=list)


class PipelineInfo(BaseModel):
    """Full description of the pipeline and its execution."""

    definition: PipelineDefinition
    run_config: PipelineRunConfig
    artifacts: list[PipelineArtifact]


class PipelineRun(BaseModel):
    """Describe a execution of a pipeline."""

    pipeline_run_id: str
    assay: str
    executed_at: datetime
    pipeline_info: PipelineInfo


class SequencingInfo(BaseModel):
    """Information on the sample was sequenced."""

    sequencing_run_id: str
    platform: str
    instrument: str | None = None
    sequencing_method: str | None = None
    sequenced_at: datetime | None = None


class AnalysisResult(BaseModel):
    """Container for analysis results."""
    software: AnalysisSoftware
    software_version: str

    # how it was parsed
    parser_name: str
    parser_version: int
    parser_status: str
    reason: str | None = None

    # results
    analysis_type: AnalysisType
    results: Any


class GenericMetadataRecord(BaseModel):
    """Canonical internal representation of simple metadata values."""

    fieldname: str
    value: str | int | float | datetime
    category: str | None = None
    data_type: Literal["string", "integer", "float", "datetime"]


class TabularMetadataRecord(BaseModel):
    fieldname: str
    columns: list[str]
    rows: list[str] | None = None
    cells: list[list[Any]]
    category: str | None = None
    data_type: Literal["table"] = "table"


InternalMetadataRecord: TypeAdapter = GenericMetadataRecord | TabularMetadataRecord

class ParsedSampleResults(BaseModel):
    """Internal representation of a parsed sample."""
    schema_version: Literal[3] = 3

    sample_id: str
    sample_name: str
    lims_id: str

    # metadata
    metadata: list[InternalMetadataRecord] = Field(..., default_factory=list)
    sequencing: SequencingInfo
    pipeline: PipelineRun

    # analysis results
    analysis_results: list[AnalysisResult] = Field(..., default_factory=list)
