"""Sample manifest info."""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from bonsai_libs.api_client.bonsai.models import (
    CreateGroupInput,
    CreateReferenceGenomeInput,
    CreateUserInput,
)
from pydantic import BaseModel, Field, ValidationInfo
from pydantic_core import core_schema

from .base import AllowExtraModelMixin, RelOrAbsPath
from .metadata import MetaEntry

LOG = logging.getLogger(__name__)


@dataclass
class URI:
    """Uniform Resource Identifier for files generated by the pipeline."""

    scheme: str
    path: str
    netloc: str = ""

    def __str__(self):
        return f"{self.scheme}://{self.path}"


class FlexibleURI:
    """
    Accepts:
    - relative or absolute local paths → file://
    - file:// URIs
    - http(s)://
    - s3://
    Returns: URI(scheme, netloc, path)
    """

    @classmethod
    def validate(cls, value: Any, info: ValidationInfo):
        """Convert flexible URI input into a standardized URI object."""
        if isinstance(value, Path):
            value = str(value)

        if isinstance(value, str):
            p = Path(value)

            # Absolute paths don't need to exist yet: the access/symlink dir may not
            # be mounted at manifest-read time. Only warn, since bonsai upload reads
            # analysis-result files later and index artifacts aren't read at all.
            if p.is_absolute():
                if not p.exists():
                    LOG.warning(
                        "File not found at %s (not yet symlinked?); accepting as file:// URI",
                        p,
                    )
                pr = urlparse(f"file://{p.as_posix()}")
                return URI(pr.scheme, pr.path, pr.netloc)

            if info.context:
                p = (Path(info.context.parent) / p).resolve()
                if p.exists():
                    pr = urlparse(f"file://{p.as_posix()}")
                    return URI(pr.scheme, pr.path, pr.netloc)

        pr = urlparse(value)
        if pr.scheme:
            return URI(pr.scheme, pr.path, pr.netloc)

        raise ValueError(f"Invalid URI or path: {value}")

    @classmethod
    def __get_pydantic_core_schema__(cls, _source, _handler):
        return core_schema.with_info_plain_validator_function(cls.validate)


class IgvAnnotation(BaseModel):
    """Format of a IGV annotation track."""

    name: str | None = None
    format: str | None = None
    type: str
    uri: str
    index_uri: str | None = None


class AnalysisResult(BaseModel):
    """Describe how a analysis result was derived."""

    software: str
    software_version: str
    database: str | None = None
    uri: FlexibleURI


class IndexArtifacts(BaseModel):
    """Index files generated by the pipeline."""

    ska_index: FlexibleURI | None = None
    sourmash_signature: FlexibleURI | None = None


class SampleManifest(AllowExtraModelMixin):
    """Sample information with metadata and results files."""

    sample_id: str = Field(..., min_length=3, max_length=100)
    sample_name: str
    lims_id: str

    groups: list[str] = Field(default_factory=list)
    metadata: list[MetaEntry] = Field(default_factory=list)

    reference_genome_id: str | None = None
    igv_annotations: list[IgvAnnotation] = Field(default_factory=list)

    nextflow_run_info: RelOrAbsPath

    analysis_result: list[AnalysisResult] = Field(
        default_factory=list,
        description="Analysis results produced by the pipeline",
    )

    index_artifacts: IndexArtifacts | None = None

    def assigned_to_group(self) -> bool:
        """Return True if sample is assigned to a group."""
        return len(self.groups) > 0


class BootstrapConfig(BaseModel):
    """Definition of informaiton required to bootstrap Bonsai."""

    users: list[CreateUserInput] = Field(default_factory=list)
    groups: list[CreateGroupInput] = Field(default_factory=list)
    reference_genomes: list[CreateReferenceGenomeInput] = Field(default_factory=list)
