# This workflow will install PRP and run the test suite on three versions of python

name: Pytest

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Run test suite
      run: |
        pytest --cov-fail-under 70 tests